package au.org.tso.ldap.navigator;

import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import org.apache.directory.ldap.client.api.LdapConnection;
import org.slf4j.LoggerFactory;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 * Navigator
 * 
 * The interface between the javscript interface and the server
 */
@SpringBootApplication
@RestController
@ComponentScan("au.org.tso.ldap.navigator")
@RequestMapping("navigator")
public class Navigator {

	/**
	 * Thrown if the HTTP page could not be found
	 * ResourceNotFoundException
	 */
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public class ResourceNotFoundException extends RuntimeException {
		/**
		 * HTTP resource not found
		 * @param message the generic message for a page not found
		 */
		public ResourceNotFoundException(String message) {
			super(message);
		}
	}

	/**
	 * ExceptionControllerAdvice
	 * 
	 * Manages exceptions generated by other classes
	 */
	@ControllerAdvice
	public class ExceptionControllerAdvice {

		/**
		 * REST exception handler for a resource not found
		 * 
		 * @param ex the exception thrown by an internal class
		 * @return the wrapped exception
		 */
		@ExceptionHandler(ResourceNotFoundException.class)
		public ResponseEntity<String> handleResourceNotFoundException(ResourceNotFoundException ex) {

			return new ResponseEntity<>(ex.getMessage(), HttpStatus.NOT_FOUND);
		}

		/**
		 * Generic REST exception handler
		 * 
		 * @param ex the exception thrown by an internal class
		 * @return the wrapped exception
		 */
		@ExceptionHandler(Exception.class)
		public ResponseEntity<String> handleGenericException(Exception ex) {
			var logger = LoggerFactory.getLogger(Navigator.class);
			logger.error(ex.getMessage());

			return new ResponseEntity<>(ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
		}
	}

	final ConnectionManager connectionManager;
	final DirectoryExplorer directoryExplorer;
	final DirectoryExporter directoryExporter;

	/**
	 * Navigator constructor
	 * 
	 * @param connectionManager the connection manager
	 * @param directoryExplorer the directory explorer
	 * @param directoryExporter the directory exporter
	 * 
	 */
	Navigator(ConnectionManager connectionManager, DirectoryExplorer directoryExplorer,
			DirectoryExporter directoryExporter) {
		this.connectionManager = connectionManager;
		this.directoryExplorer = directoryExplorer;
		this.directoryExporter = directoryExporter;
	}

	@GetMapping("/connect")
	HashMap<String, String> connect(@RequestParam("url") String url,
			@RequestHeader("password") String password) throws Exception {
		HashMap<String, String> parts = connectionManager.parse(url);

		connectionManager.reconnect(url);

		return parts;

	}

	@GetMapping("/status")
	String status(@RequestParam("url") String url, @RequestHeader("password") String password) throws Exception {

		connectionManager.parse(url);

		return Integer.toString(connectionManager.status(url));

	}

	@GetMapping("/search")
	SearchResponse search(@RequestParam("url") String url,
			@RequestHeader("password") String password,
			@RequestParam("argument") String argument,
			@RequestParam("limit") String limit) throws Exception {
		var logger = LoggerFactory.getLogger(Navigator.class);

		logger.info("Search Started: '" + argument + "'");

		LdapConnection connection = connectionManager.connect(url, password);

		SearchResponse response = directoryExplorer.search(connection, argument, Integer.parseInt(limit));

		logger.info("Search Successful: {} : {} ", limit, response.getResults().size());

		return response;

	}

	@GetMapping("/retrieve")
	Vector<Map<String, String>> retrieve(@RequestParam("url") String url,
			@RequestHeader("password") String password,
			@RequestParam("argument") String argument)
			throws Exception {
		var logger = LoggerFactory.getLogger(Navigator.class);

		logger.info("Retrieve Started");

		LdapConnection connection = connectionManager.connect(url, password);

		Vector<Map<String, String>> attributes = directoryExplorer.retrieve(connection, argument);

		logger.info("Retrieve Successful: " + attributes.size());

		return attributes;

	}

	@GetMapping("/export")
	byte[] export(@RequestParam("url") String url, @RequestHeader("password") String password,

			@RequestParam("dn") String dn) throws Exception {
		var logger = LoggerFactory.getLogger(Navigator.class);

		logger.info("Export Started");

		LdapConnection connection = connectionManager.connect(url, password);

		var exportValue = directoryExporter.export(connection, dn);

		return exportValue;

	}

	/**
	 * Main method
	 * 
	 * @param args no used for this application
	 */
	public static void main(String[] args) {

		SpringApplication.run(Navigator.class, args);

	}

}
